### PR TITLE
Use argpase for providing values

### PR DESCRIPTION
**Pull request by Ashex1**
Pretty basic change, instead of hardcoding stuff in the example script just pass them as arguments.

### CODE REVIEW

**Comment by Ashex1** [comment]
@aktarer Thoughts on getting this merged in? It is the example script so not necessarily part of the project but is still nice to have it in a state that people can use it out of the box.

**Comment by aktarer** [comment]
Great idea! However, we'd like to keep `example.py` minimal. How about a different file, like `example_from_args.py`?

**Comment by Ashex1** [comment]
Yeah, I was thinking of calling it `client_example.py` but `example_from_args.py` is totally fine. Lemme know which you prefer and I'll submit a new PR.

**Comment by Ashex1** [comment]
If a second file were created they'd have almost identical code, only difference being a class wrapper and argparse. 

If you prefer it that way then it can be done, just seems like it'll add some clutter.

**Comment by aktarer** [comment]
Yeah, a second file is preferable. Having a super simple example to showcase the lib is worth it I think.

**Comment by Ashex1** [comment]
Okay, I'll submit another PR with the new file.

**Pull request closed without merging**
